apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, get, *, allow
    p, role:admin, clusters, create, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, certificates, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, logs, *, *, allow
    p, role:admin, exec, *, *, allow
    
    p, role:developer, applications, *, */*, allow
    p, role:developer, applications, get, *, allow
    p, role:developer, applications, create, *, allow
    p, role:developer, applications, update, */*, allow
    p, role:developer, applications, delete, */*, allow
    p, role:developer, applications, sync, */*, allow
    p, role:developer, applications, override, */*, allow
    p, role:developer, clusters, get, *, allow
    p, role:developer, repositories, get, *, allow
    p, role:developer, repositories, create, *, allow
    p, role:developer, logs, get, */*, allow
    p, role:developer, exec, create, */*, allow
    
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, logs, get, */*, allow
    
    p, role:sync-only, applications, sync, */*, allow
    p, role:sync-only, applications, get, */*, allow
    p, role:sync-only, applications, override, */*, allow
    p, role:sync-only, repositories, get, *, allow
    p, role:sync-only, clusters, get, *, allow
    
    g, role:admin, "*"
    g, sarath@github.com, role:admin
    g, platform-team@github.com, role:developer
    g, developers@github.com, role:readonly
  scopes: "[groups]"
